Reporting errors

diff --git a/.github/workflows/commands.yml b/.github/workflows/commands.yml
--- a/.github/workflows/commands.yml
+++ b/.github/workflows/commands.yml
@@ -79,7 +79,26 @@ jobs:
         if: steps.get_round.outputs.result == 'builddoc'
         run: |
           cd build_doc
-          make -j 2 doc
+          make -j 2 doc  > buildDoc.log
+
+      - name: Checking doc
+        id: checking-doc
+        run: |
+            pwd
+            export BUILD_DIR=${{runner.workspace}}/DGtal/build_doc
+            export SRC_DIR=${{runner.workspace}}/DGtal/
+            .github/workflows/checkDoxygenDocumentation.sh
+             if [ -s tmp.log ]; then
+              content=`cat /tmp/doxygen.kept.log`
+              delimiter="$(openssl rand -hex 8)"
+              echo "DoxygenError<<${delimiter}" >> "${GITHUB_OUTPUT}"
+              cat tmp.log >> "${GITHUB_OUTPUT}"
+              echo "${delimiter}" >> "${GITHUB_OUTPUT}"
+              exit 1
+            fi
+
+      - name: Preparing Deploy
+        run: |
           mkdir pr${{ steps.get_pr_number.outputs.result }}
           mv html/* pr${{ steps.get_pr_number.outputs.result }}/
           git clone --depth 2 https://github.com/DGtal-team/doc-nightly.git
@@ -115,7 +134,7 @@ jobs:
 
       - name: Post error
         env:
-          ERRORMSG: ${{steps.build_and_run.outputs.DoxygenError}}
+          ERRORMSG: ${{steps.checking-doc.outputs.DoxygenError}}
         uses: actions/github-script@v6
         if: ${{ failure() && steps.get_round.outputs.result == 'builddoc' }}
         with:
